/** 从 Inspector 公开入口到右栏内容与会话状态，不执行桌面视觉验收。 */
import assert from "node:assert/strict";
import { test } from "node:test";
import { registerHooks } from "node:module";

test("渲染预览打开真实右栏，保留预览状态并按会话隔离", async () => {
  const { JSDOM } = await import("jsdom");
  const dom = new JSDOM("<!doctype html><div id='root'></div>", { pretendToBeVisual: true, url: "https://localhost/" });
  const globals = globalThis as unknown as Record<string, unknown>;
  for (const key of ["window", "document", "MutationObserver", "DOMParser", "XMLSerializer", "Node", "Element", "HTMLElement", "SVGElement", "DocumentFragment", "MouseEvent", "Event", "getComputedStyle"]) globals[key] = (dom.window as unknown as Record<string, unknown>)[key];
  Object.defineProperty(globalThis, "navigator", { configurable: true, value: dom.window.navigator });
  Object.assign(dom.window, { matchMedia: () => ({ matches: false, addEventListener() {}, removeEventListener() {} }) });
  globals.ResizeObserver = class { observe() {} disconnect() {} };
  Object.defineProperty(dom.window.HTMLElement.prototype, "clientWidth", { get() { return 1200; } });
  Object.defineProperty(dom.window.HTMLElement.prototype, "setPointerCapture", { value() {} });
  const pointer = (type: string, clientX: number) => { const event = new dom.window.MouseEvent(type, { clientX, bubbles: true, cancelable: true }); Object.defineProperty(event, "pointerId", { value: 1 }); return event; };
  const React = await import("react"); Object.assign(globalThis, { React });
  const { createRoot } = await import("react-dom/client");
  const { flushSync } = await import("react-dom");
  const hooks = registerHooks({
    resolve(specifier, context, next) { return specifier === "@xterm/xterm" || specifier === "@xterm/addon-fit" ? { url: `test:${specifier}`, shortCircuit: true } : next(specifier, context); },
    load(url, context, next) { return url.startsWith("test:") ? { format: "module", shortCircuit: true, source: "export class Terminal {} export class FitAddon {}" } : url.endsWith(".css") ? { format: "module", shortCircuit: true, source: "export {};" } : next(url, context); }
  });
  const { useWorkspaceInspector } = await import("../src/desktop/renderer/src/components/workspace/useWorkspaceInspector.js");
  const { MermaidBlock } = await import("../src/desktop/renderer/src/components/MermaidBlock.js");
  type Inspector = ReturnType<typeof useWorkspaceInspector> & { previewRendering?: (preview: { id: string; title: string; source: string; language: string; filename: string; renderPreview(): React.ReactNode }) => void };
  let inspector: Inspector;
  let reads = 0;
  let listings = 0;
  const options = { changes: [], tools: [], filePanelResizing: false, filePanelWidth: 460, projectId: "p", onFilePanelResizeEnd() {}, onFilePanelResizeStart() {}, onFilePanelWidthChange() {}, async onListDirectory() { listings++; return { path: ".", entries: [] }; }, onOpenFile() {}, async onOpenBrowser() {}, onFixPreview() {}, async onSwitchBranch() {}, async onReadFile() { reads++; throw new Error("should not read files"); }, onWarning() {} };
  function Probe({ id = "probe", label = "Count" }: { id?: string; label?: string } = {}) { const [count, setCount] = React.useState(0); return React.createElement("button", { id, onClick: () => setCount(value => value + 1) }, `${label} ${count}`); }
  function PreviewDiagram({ code, id, label }: { code: string; id?: string; label?: string }) { return React.createElement(React.Fragment, null, React.createElement(Probe, { id, label }), React.createElement(MermaidBlock, { code })); }
  function Harness({ source, projectId = "p" }: { source: string; projectId?: string }) { inspector = useWorkspaceInspector({ ...options, projectId, source }); return React.createElement("div", { className: "biny-app-shell" }, React.createElement("button", { id: "origin" }, "Open"), inspector.dock); }
  const root = createRoot(document.getElementById("root")!);
  const render = (source: string, projectId = "p") => flushSync(() => root.render(React.createElement(Harness, { source, projectId })));
  try {
    render("p:first");
    assert.equal(typeof inspector!.previewRendering, "function", "右栏必须有直接预览渲染快照的公开入口");
    const origin = document.getElementById("origin")!; origin.focus();
    const preview = { id: "diagram", title: "时序图", source: "sequenceDiagram\nA->>B: hi", language: "mermaid", filename: "diagram.mmd", renderPreview: () => React.createElement(PreviewDiagram, { code: "sequenceDiagram\nA->>B: hi" }) };
    flushSync(() => inspector!.previewRendering!(preview));
    assert.equal(inspector!.layout.open, true);
    assert.equal(inspector!.layout.width, 420);
    assert.equal(document.querySelector('[aria-label="渲染预览"]')?.textContent?.includes("时序图"), true);
    assert.equal(reads, 0); assert.equal(listings, 0);
    const resizer = document.querySelector<HTMLElement>('[aria-label="调整检查器宽度"]')!;
    flushSync(() => resizer.dispatchEvent(pointer("pointerdown", 900)));
    assert.equal(inspector!.layout.resizing, true);
    flushSync(() => dom.window.dispatchEvent(pointer("pointermove", 720)));
    assert.equal(inspector!.layout.width, 600);
    flushSync(() => dom.window.dispatchEvent(pointer("pointerup", 720)));
    assert.equal(inspector!.layout.resizing, false);
    for (let step = 0; step < 20; step++) flushSync(() => resizer.dispatchEvent(new dom.window.KeyboardEvent("keydown", { key: "ArrowRight", bubbles: true })));
    assert.equal(inspector!.layout.width, 300);
    for (let step = 0; step < 65; step++) flushSync(() => resizer.dispatchEvent(new dom.window.KeyboardEvent("keydown", { key: "ArrowLeft", bubbles: true })));
    assert.equal(inspector!.layout.width, 1200, "渲染右栏宽度以窗口可用宽度为限，不套用文件栏上限");
    const probe = document.getElementById("probe")!;
    flushSync(() => probe.click());
    const firstSvg = document.querySelector('[data-rendering-id="diagram"] .markdown-mermaid svg');
    const firstZoom = document.querySelector<HTMLButtonElement>('[data-rendering-id="diagram"] [aria-label="放大图表"]')!;
    flushSync(() => firstZoom.click());
    flushSync(() => document.querySelector<HTMLButtonElement>('button[aria-label="查看源码"]')!.click());
    assert.equal(document.getElementById("probe"), probe);
    assert.equal(probe.textContent, "Count 1");
    assert.ok(document.querySelector('[data-rendering-source]')?.textContent?.includes("A->>B: hi"));
    flushSync(() => document.querySelector<HTMLButtonElement>('button[aria-label="查看预览"]')!.click());
    assert.equal(document.getElementById("probe"), probe);
    flushSync(() => document.querySelector<HTMLButtonElement>('button[aria-label="查看源码"]')!.click());
    origin.focus();
    const second = { ...preview, id: "diagram-two", title: "流程图", source: "flowchart TD\nStart-->Done", renderPreview: () => React.createElement(PreviewDiagram, { code: "flowchart TD\nStart-->Done", id: "probe-two", label: "Other" }) };
    flushSync(() => inspector!.previewRendering!(second));
    const tabs = () => [...document.querySelectorAll<HTMLButtonElement>('[aria-label="图表标签"] [role="tab"]')];
    assert.equal(tabs().length, 2, "不同图必须新增标签");
    assert.equal(document.getElementById("probe"), probe, "切换图保留原预览 DOM");
    const secondProbe = document.getElementById("probe-two")!;
    flushSync(() => secondProbe.click());
    const secondSvg = document.querySelector('[data-rendering-id="diagram-two"] .markdown-mermaid svg');
    const secondZoom = document.querySelector<HTMLButtonElement>('[data-rendering-id="diagram-two"] [aria-label="放大图表"]')!;
    flushSync(() => secondZoom.click()); flushSync(() => secondZoom.click());
    const select = (title: string) => flushSync(() => tabs().find(tab => tab.textContent?.includes(title))!.click());
    select("时序图");
    assert.equal(document.querySelector('[aria-label="查看源码"]')?.getAttribute("aria-pressed"), "true", "各图保留独立源码显示方式");
    assert.equal(probe.textContent, "Count 1");
    assert.equal(document.querySelector('[data-rendering-id="diagram"] .markdown-mermaid svg'), firstSvg);
    assert.equal(document.querySelector('[data-rendering-id="diagram"] .markdown-diagram-scale')?.textContent, "125%");
    flushSync(() => document.querySelector<HTMLButtonElement>('button[aria-label="查看预览"]')!.click());
    select("流程图");
    assert.equal(document.querySelector('[aria-label="查看预览"]')?.getAttribute("aria-pressed"), "true");
    assert.equal(document.getElementById("probe-two"), secondProbe); assert.equal(secondProbe.textContent, "Other 1");
    assert.equal(document.querySelector('[data-rendering-id="diagram-two"] .markdown-mermaid svg'), secondSvg);
    assert.equal(document.querySelector('[data-rendering-id="diagram-two"] .markdown-diagram-scale')?.textContent, "150%");
    origin.focus();
    flushSync(() => inspector!.previewRendering!({ ...preview, title: "更新图", source: "sequenceDiagram\nA->>B: updated", renderPreview: () => React.createElement(PreviewDiagram, { code: "sequenceDiagram\nA->>B: updated", label: "Updated" }) }));
    assert.equal(tabs().length, 2, "同 id 更新已有标签");
    assert.equal(document.getElementById("probe"), probe); assert.equal(probe.textContent, "Updated 1");
    assert.equal(document.querySelector('[data-rendering-id="diagram"] .markdown-diagram-scale')?.textContent, "125%");
    assert.equal(document.querySelector('[data-rendering-id="diagram"] [data-rendering-source]')?.textContent?.includes("updated"), true);
    origin.focus();
    const third = { ...second, id: "diagram-three", title: "第三图", renderPreview: () => React.createElement(PreviewDiagram, { code: "flowchart TD\nThird-->Done", id: "probe-three" }) };
    flushSync(() => inspector!.previewRendering!(third));
    assert.equal(tabs().length, 3);
    flushSync(() => document.querySelector<HTMLButtonElement>('button[aria-label="关闭图表 第三图"]')!.click());
    assert.equal(tabs().length, 2); assert.equal(document.getElementById("probe-three"), null);
    assert.equal(tabs().find(tab => tab.getAttribute("aria-selected") === "true")?.textContent?.includes("更新图"), true, "关闭活动图后选择首个剩余图");
    flushSync(() => document.querySelector<HTMLButtonElement>('button[aria-label="关闭图表 流程图"]')!.click());
    assert.equal(document.getElementById("probe-two"), null, "关闭标签释放该图 DOM");
    assert.equal(document.getElementById("probe"), probe); assert.equal(tabs().length, 0, "只剩一图时隐藏标签条");
    flushSync(() => document.querySelector<HTMLButtonElement>('button[aria-label="展开预览全屏"]')!.click());
    assert.equal(inspector!.layout.focused, true);
    flushSync(() => document.querySelector<HTMLButtonElement>('button[aria-label="退出预览全屏"]')!.click());
    assert.equal(inspector!.layout.focused, false);
    flushSync(() => document.querySelector<HTMLButtonElement>('button[aria-label="关闭预览"]')!.click());
    assert.equal(inspector!.layout.open, false);
    assert.equal(document.activeElement, origin);
    flushSync(() => inspector!.previewRendering!(preview));
    assert.equal(document.getElementById("probe"), probe, "关闭面板保留同会话预览状态，重新打开不重挂载");
    assert.equal(probe.textContent, "Count 1");
    flushSync(() => resizer.dispatchEvent(pointer("pointerdown", 1200)));
    render("p:second");
    assert.equal(inspector!.layout.open, false);
    assert.equal(document.getElementById("probe"), null);
    flushSync(() => dom.window.dispatchEvent(pointer("pointermove", 1300)));
    flushSync(() => inspector!.previewRendering!(preview));
    assert.equal(inspector!.layout.width, 1200, "离开会话必须注销尚未结束的拖动");
    flushSync(() => document.querySelector<HTMLButtonElement>('button[aria-label="关闭预览"]')!.click());
    const stale = inspector!.previewRendering!;
    render("other:third", "other");
    flushSync(() => stale(preview));
    assert.equal(inspector!.layout.open, false, "旧会话入口不能把旧快照写入新项目");
  } finally { flushSync(() => root.unmount()); hooks.deregister(); dom.window.close(); }
});
