/** 规划限制及候选绑定走真实工具协调器、文件和 TaskRun 存储；不调用模型。 */
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { ToolExecutionCoordinator } from "../src/agent/toolExecutionCoordinator.js";
import { defaultConfig } from "../src/config/schema.js";
import { PermissionManager } from "../src/permission/PermissionManager.js";
import { SessionRecorder } from "../src/session/recorder.js";
import { readSessionEvents } from "../src/session/events.js";
import { ensureAgentDirs } from "../src/session/store.js";
import { createToolRegistry } from "../src/tools/registry.js";
import { RuntimeEventAuthority } from "../src/runtime/RuntimeAuthority.js";
import { DurableTaskRunStore } from "../src/runtime/TaskRunStore.js";
import { runTaskClosure } from "../src/runtime/TaskClosure.js";
import { readTaskDefinition, type TaskCommandExecutor, type TaskVerificationContract } from "../src/runtime/taskVerification.js";
import type { PlanReviewCandidate } from "../src/runtime/planWork.js";
import { createPlanTools } from "../src/extensions/plan.js";
import { GoalGraphStore } from "../src/runtime/GoalGraphStore.js";

const root = await mkdtemp(path.join(os.tmpdir(), "biny-plan-safety-"));
await ensureAgentDirs(root);
const authority = await RuntimeEventAuthority.open(root);
const tasks = await DurableTaskRunStore.open(root, authority);
const graphs = await GoalGraphStore.open(root, authority);
const recorder = new SessionRecorder(root, "plan-safety", undefined, authority.asSink());
const config = structuredClone(defaultConfig);
config.permission.mode = "full-access";
config.permission.criticalAlwaysAsk = false;
// 本测试覆盖规划安全和验收闭环，不测依赖 macOS Seatbelt 的默认路径禁令。
config.permission.denyPaths = [];
config.sandbox.mode = "off";
const registry = createToolRegistry({ workspaceRoot: root, ignore: [".biny"] }, undefined, undefined, undefined, config.sandbox);
const permissions = new PermissionManager(config.permission);
try {
  // 只读报告不需要命令验收，但必须保留验收标准，不能携带伪造的独立评审门。
  const start = createPlanTools({ graphs, taskRuns: tasks }).find((tool) => tool.name === "PlanStart")!;
  const reportNode = { key: "inspect", task: "Read a.txt and explain it", acceptance: ["Cite a.txt and distinguish observations from inference"] };
  const reportPlan = { objective: "Understand the local input", nodes: [reportNode, { ...reportNode, key: "synthesize", dependencies: ["inspect"] }] };
  const parsed = start.schema!.parse(reportPlan);
  assert.throws(() => start.schema!.parse({ ...reportPlan, nodes: [{ ...reportNode, acceptance: undefined }, reportPlan.nodes[1]] }));
  assert.throws(() => start.schema!.parse({ ...reportPlan, nodes: [{ ...reportNode, review: "review" }, reportPlan.nodes[1]] }));
  const execution = await start.resolveExecution(parsed);
  if ("isError" in execution) throw new Error(execution.errorMessage);
  await execution.execute({ toolCallId: "report-plan", operationId: "report-plan", sessionId: "reports", runId: "reports" });
  const graph = graphs.listGraphs()[0]!;
  const intent = graph.nodes[0]!.intent;
  const reportTask = tasks.create({ task: intent });
  const reportInput = { taskRuns: tasks, taskRunId: reportTask.taskRunId, workspaceRoot: root, ignore: [".biny"], executor: { executeTaskCheck: async (): Promise<never> => { throw new Error("Reports must not execute checks."); } } };
  const reportResult = await runTaskClosure({ ...reportInput, executeAttempt: async () => "a.txt: observed input; conclusion remains subject to supervisor review." });
  assert.equal(reportResult.status, "completed");
  assert.equal(reportResult.evidence, undefined);
  assert.match(reportResult.output!, /a.txt/u);
  const reused = await runTaskClosure({ ...reportInput, executeAttempt: async () => { throw new Error("Completed report must not rerun."); } });
  assert.equal(reused.output, reportResult.output);
  // 进程在 TaskRun 完成后、Graph 投影前退出：恢复同一份报告，再放行下游。
  graphs.claimIntent(graph.graphId, graph.nodes[0]!.nodeId, "report-claim", reportTask.taskRunId);
  graphs.recoverRunningNodes(tasks);
  assert.equal(graphs.inspectGraph(graph.graphId).nodes[0]?.status, "ready");
  graphs.claimIntent(graph.graphId, graph.nodes[0]!.nodeId, "report-recovery", reportTask.taskRunId);
  graphs.projectTaskClosure(reportTask.taskRunId, reused);
  assert.deepEqual(graphs.readyNodes(graph.graphId).map((node) => node.nodeKey), ["synthesize"]);
  const secondNode = graphs.readyNodes(graph.graphId)[0]!;
  graphs.claimIntent(graph.graphId, secondNode.nodeId);
  graphs.completeNode(graph.graphId, secondNode.nodeId, "failed");
  const replaced = graphs.replaceSupervisedNode(graph.graphId, "reports", secondNode.nodeId, { nodeKey: "retry-report", prompt: "Reinspect the evidence" });
  const replacement = replaced.nodes.find((node) => node.replacesNodeId === secondNode.nodeId)!;
  assert.equal(readTaskDefinition(replacement.intent).reportOnly, true);
  assert.deepEqual((replacement.intent as { planBlock: { acceptance: string[] } }).planBlock.acceptance, reportNode.acceptance);
  const empty = tasks.create({ task: intent });
  const emptyResult = await runTaskClosure({ ...reportInput, taskRunId: empty.taskRunId, executeAttempt: async () => "  " });
  assert.equal(emptyResult.status, "blocked");
  assert.equal(tasks.get(empty.taskRunId)?.status, "blocked");
  const persisted = tasks.create({ task: intent });
  const persistedAttempt = tasks.createAttempt(persisted.taskRunId);
  tasks.transition(persisted.taskRunId, "running", { attemptId: persistedAttempt.attemptId });
  tasks.transition(persisted.taskRunId, "verifying", { attemptId: persistedAttempt.attemptId, artifacts: { output: "persisted report" } });
  const recoveredReport = await runTaskClosure({ ...reportInput, taskRunId: persisted.taskRunId, executeAttempt: async () => { throw new Error("Recover output, do not rerun worker."); } });
  assert.equal(recoveredReport.output, "persisted report");
  assert.equal(tasks.get(persisted.taskRunId)?.attempts.length, 1);
  const cancelled = tasks.create({ task: intent });
  const cancelledReport = await runTaskClosure({ ...reportInput, taskRunId: cancelled.taskRunId, executeAttempt: async (_prompt, attempt) => {
    tasks.transition(cancelled.taskRunId, "cancelled", { attemptId: attempt.attemptId });
    return "late output";
  } });
  assert.equal(cancelledReport.status, "cancelled");
  assert.equal(tasks.get(cancelled.taskRunId)?.status, "cancelled");

  await writeFile(path.join(root, "a.txt"), "good");
  const planningConfig = structuredClone(config);
  planningConfig.hooks.beforeTool = [{ command: "touch hook-ran", tools: [], extensions: [], timeoutMs: 1000 }];
  planningConfig.hooks.afterTool = planningConfig.hooks.beforeTool;
  const planner = new ToolExecutionCoordinator({ workspaceRoot: root, config: planningConfig, recorder, toolRegistry: registry, planning: true }, permissions, () => undefined);
  assert.ok(!planner.createAgentTools().some((tool) => ["Bash", "Write", "Edit"].includes(tool.name)));
  planner.allowTools(["Bash", "Write"]);
  assert.ok(!planner.createAgentTools().some((tool) => tool.name === "Write"), "ToolSearch expansion cannot expose writes");
  await planner.handleInvalidToolCall("Write", "forged-write", { path: "a.txt", content: "changed" });
  await planner.handleInvalidToolCall("Bash", "forged-bash", { command: "touch executed" });
  const read = planner.createAgentTools().find((tool) => tool.name === "Read")!;
  assert.equal((await read.execute("read", { path: "a.txt" })).isError, false);
  await planner.waitForIdle();
  await recorder.flush();
  assert.equal(await readFile(path.join(root, "a.txt"), "utf8"), "good");
  await assert.rejects(readFile(path.join(root, "executed")), /ENOENT/u);
  await assert.rejects(readFile(path.join(root, "hook-ran")), /ENOENT/u);
  const events = await readSessionEvents(recorder.filePath);
  assert.ok(events.some((event) => event.type === "tool_call" && event.toolCallId === "forged-write"));
  assert.ok(events.some((event) => event.type === "tool_result" && event.toolCallId === "forged-write" && event.executionStatus === "failed"));

  const executor: TaskCommandExecutor = { async executeTaskCheck(input) {
    const coordinator = new ToolExecutionCoordinator({ workspaceRoot: root, config, recorder, toolRegistry: registry, runId: input.taskRunId, turnId: input.attemptId }, permissions, () => undefined);
    const toolCallId = `${input.attemptId}:${input.checkId}`;
    const result = await coordinator.createAgentTools().find((tool) => tool.name === "Bash")!.execute(toolCallId, { command: input.command, cwd: "." });
    await recorder.flush();
    return { result: result.details, toolCallId, eventReferences: [toolCallId] };
  } };
  const contract: TaskVerificationContract = { version: 1, objective: "a.txt is good", artifactPaths: ["a.txt"], allowedRepairPaths: ["a.txt"], checks: [{ id: "content", command: "test \"$(cat a.txt)\" = good", definitionPaths: [] }], maxAttempts: 1 };
  const source = tasks.create({ task: { prompt: "produce candidate", verification: contract } });
  const result = await runTaskClosure({ taskRuns: tasks, taskRunId: source.taskRunId, workspaceRoot: root, ignore: [".biny"], executor, executeAttempt: async () => "candidate" });
  assert.equal(result.status, "completed");
  const candidate: PlanReviewCandidate = { taskRunId: source.taskRunId, attemptId: tasks.get(source.taskRunId)!.attempts[0]!.attemptId, contract, evidence: result.evidence! };
  const verdict = (value: string, findings: unknown[] = [], evidenceReferences = ["a.txt"]) => JSON.stringify({ verdict: value, summary: "review report", evidenceReferences, findings });
  const review = async (output: string, mutate = false) => {
    const task = tasks.create({ task: { prompt: "review only", review: candidate } });
    const completion = await runTaskClosure({ taskRuns: tasks, taskRunId: task.taskRunId, workspaceRoot: root, ignore: [".biny"], executor, executeAttempt: async () => {
      if (mutate) await writeFile(path.join(root, "a.txt"), "changed outside reviewer");
      return output;
    } });
    return { task, completion };
  };
  const accepted = await review(verdict("passed"));
  assert.equal(accepted.completion.review?.verdict, "passed");
  const resumed = await runTaskClosure({ taskRuns: tasks, taskRunId: accepted.task.taskRunId, workspaceRoot: root, ignore: [".biny"], executor, executeAttempt: async () => { throw new Error("must not rerun reviewer"); } });
  assert.equal(resumed.review?.verdict, "passed");
  const interrupted = tasks.create({ task: { prompt: "recover persisted review output", review: candidate } });
  const interruptedAttempt = tasks.createAttempt(interrupted.taskRunId);
  tasks.transition(interrupted.taskRunId, "running", { attemptId: interruptedAttempt.attemptId });
  tasks.transition(interrupted.taskRunId, "verifying", { attemptId: interruptedAttempt.attemptId, artifacts: { output: verdict("passed") } });
  const recovered = await runTaskClosure({ taskRuns: tasks, taskRunId: interrupted.taskRunId, workspaceRoot: root, ignore: [".biny"], executor, executeAttempt: async () => { throw new Error("persisted review must not rerun"); } });
  assert.equal(recovered.review?.verdict, "passed");
  assert.equal(tasks.get(interrupted.taskRunId)?.attempts.length, 1);
  const rejected = await review(verdict("needs_changes", [{ criterion: "a.txt is good", requestedChange: "add missing edge case" }]));
  assert.equal(rejected.completion.review?.verdict, "needs_changes");
  assert.equal((await review(verdict("needs_changes"))).completion.status, "blocked");
  assert.equal((await review(verdict("passed", [], ["invented.txt"]))).completion.status, "blocked");
  assert.equal((await review("not json")).completion.status, "blocked");
  const changed = await review(verdict("passed"), true);
  assert.equal(changed.completion.status, "blocked");
  assert.equal(tasks.get(changed.task.taskRunId)?.status, "blocked");
  const stale = tasks.create({ task: { prompt: "stale review", review: candidate } });
  const blocked = await runTaskClosure({ taskRuns: tasks, taskRunId: stale.taskRunId, workspaceRoot: root, ignore: [".biny"], executor, executeAttempt: async () => { throw new Error("stale candidate must not dispatch"); } });
  assert.equal(blocked.status, "blocked");
  assert.equal(tasks.get(stale.taskRunId)?.status, "blocked");
  console.log("plan safety tests passed");
} finally {
  await recorder.close(); graphs.close(); tasks.close(); authority.close();
  await rm(root, { recursive: true, force: true });
}
