import assert from "node:assert/strict";
import { runtimeCommandOperation } from "../src/runtime/commands.js";
import { slashCommandsForSurface } from "../src/runtime/commandRegistry.js";
import { buildDesktopComposerItems } from "../src/desktop/renderer/src/components/composer/desktopSlashCommands.js";
import { executeRuntimeCommand } from "../src/runtime/commands.js";
import { mkdtemp, rm, access } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { SessionGoalStore } from "../src/runtime/SessionGoalStore.js";
import { RuntimeEventAuthority } from "../src/runtime/RuntimeAuthority.js";
import { GoalGraphStore } from "../src/runtime/GoalGraphStore.js";
import type { InteractiveRuntimeHandle } from "../src/runtime/InteractiveAgentRuntime.js";
import type { CommandRuntime } from "../src/runtime/CommandRuntime.js";
import { sessionGoalActionCommand, sessionGoalSetCommand } from "../src/cli/commands/runtimeManagement.js";
import { runtimeHostPaths } from "../src/runtime/RuntimeHost.js";

assert.equal(runtimeCommandOperation("/goal"), "session.goal.get");
assert.equal(runtimeCommandOperation("/goal show"), "session.goal.get");
assert.equal(runtimeCommandOperation("/goal set finish the work\nKeep all requirements"), "session.goal.set");
assert.equal(runtimeCommandOperation("/goal pause"), "session.goal.pause");
assert.equal(runtimeCommandOperation("/goal resume"), "session.goal.resume");
assert.equal(runtimeCommandOperation("/goal clear"), "session.goal.clear");
assert.equal(runtimeCommandOperation("  ///goal\tReSuMe  "), "session.goal.resume");
assert.equal(runtimeCommandOperation("/goal get workspace-goal"), "goal.get");
assert.equal(runtimeCommandOperation("/goal pause workspace-goal"), "goal.pause");
assert.equal(runtimeCommandOperation("/goal resume workspace-goal"), "goal.resume");
assert.equal(runtimeCommandOperation("/goal cancel workspace-goal"), "goal.cancel");
assert.equal(runtimeCommandOperation("/goal 完成所有验收\n保留  两个空格"), "session.goal.set");
assert.equal(runtimeCommandOperation("/goal nonsense"), "session.goal.set");
assert.equal(runtimeCommandOperation("/goal show unexpected-id"), undefined);
assert.equal(runtimeCommandOperation("/goal set"), undefined);
assert.equal(runtimeCommandOperation("/graph resume graph-id"), "graph.resume");
assert.ok(buildDesktopComposerItems([]).some((item) => item.id === "/goal"));
assert.equal(slashCommandsForSurface("tui").find((entry) => entry.name === "/goal")?.requiresArgs, undefined);

const root = await mkdtemp(path.join(os.tmpdir(), "biny-session-goal-surface-"));
const authority = await RuntimeEventAuthority.open(root, { backfillLegacySessions: false });
const sessionGoals = await SessionGoalStore.open(root, authority);
const graphs = await GoalGraphStore.open(root, authority);
const cancellations: string[] = [];
const runtime = { getSnapshot: () => ({ info: { sessionId: "session-a" } }), cancelCurrentRun: (reason: string) => { cancellations.push(reason); } } as InteractiveRuntimeHandle;
const services = { sessionGoals, graphs } as CommandRuntime;
try {
  const empty = await executeRuntimeCommand(runtime, services, "/goal", "tui");
  assert.match(empty?.content ?? "", /没有目标/u);
  assert.deepEqual(empty?.sessionGoal, { action: "get", status: undefined });
  const entered = await executeRuntimeCommand(runtime, services, "/goal 保留完整目标\n第二行约束  与两个空格", "desktop");
  assert.deepEqual(entered?.sessionGoal, { action: "set", status: "active" });
  assert.equal(sessionGoals.get("session-a")?.objective, "保留完整目标\n第二行约束  与两个空格");
  assert.equal(sessionGoals.get("session-b"), undefined);
  const paused = await executeRuntimeCommand(runtime, services, "/goal pause", "tui");
  assert.deepEqual(paused?.sessionGoal, { action: "pause", status: "paused" });
  assert.equal(sessionGoals.get("session-a")?.status, "paused");
  assert.deepEqual(cancellations, ["paused"], "pausing an active session goal also stops its current turn");
  const edited = await executeRuntimeCommand(runtime, services, "/goal set 修改后的完整目标\n仍保持暂停", "desktop");
  assert.deepEqual(edited?.sessionGoal, { action: "set", status: "paused" }, "editing a paused goal must report its actual state");
  assert.equal(sessionGoals.get("session-a")?.objective, "修改后的完整目标\n仍保持暂停");
  const resumed = await executeRuntimeCommand(runtime, services, "/goal resume", "desktop");
  assert.deepEqual(resumed?.sessionGoal, { action: "resume", status: "active" });
  assert.equal(sessionGoals.get("session-a")?.status, "active");
  assert.deepEqual(cancellations, ["paused"], "workspace Goal control must not cancel the session goal turn");
  const workspaceGoal = graphs.createGoal("独立 workspace 目标", {}, "workspace-goal");
  const workspaceResult = await executeRuntimeCommand(runtime, services, `/goal pause ${workspaceGoal.goalId}`, "desktop");
  assert.equal(workspaceResult?.sessionGoal, undefined, "workspace Goal actions do not enter session Goal mode");
  assert.equal(graphs.getGoal(workspaceGoal.goalId)?.status, "paused");
  assert.equal(sessionGoals.get("session-a")?.status, "active");
  await assert.rejects(executeRuntimeCommand(runtime, services, "/goal clear unexpected-id", "tui"), /Usage:/u);
  await assert.rejects(sessionGoalSetCommand(root, "目标"), /--session/u);
  await assert.rejects(sessionGoalActionCommand(root, "pause"), /--session/u);
  const output: unknown[][] = [];
  const originalLog = console.log;
  console.log = (...args: unknown[]) => { output.push(args); };
  try {
    await sessionGoalActionCommand(root, "show", { session: "session-a", json: true });
    const record = JSON.parse(String(output.at(-1)?.[0])) as { objective: string; sessionId: string };
    assert.equal(record.objective, sessionGoals.get("session-a")?.objective);
    assert.equal(record.sessionId, "session-a");
    await sessionGoalActionCommand(root, "show", { session: "missing" });
    assert.equal(output.at(-1)?.[0], "No goal for this session.");
  } finally { console.log = originalLog; }
  await assert.rejects(access(runtimeHostPaths(root).registrationPath), { code: "ENOENT" }, "read-only CLI must not spawn a Runtime Host");
  const cleared = await executeRuntimeCommand(runtime, services, "/goal clear", "desktop");
  assert.deepEqual(cleared?.sessionGoal, { action: "clear" });
  assert.equal(sessionGoals.get("session-a"), undefined);
  assert.deepEqual(cancellations, ["paused", "paused"], "clearing an active session goal also stops its current turn");
  assert.equal(graphs.getGoal(workspaceGoal.goalId)?.status, "paused");
  await executeRuntimeCommand(runtime, services, "/goal clear", "desktop");
  assert.deepEqual(cancellations, ["paused", "paused"], "clearing a missing goal must not cancel unrelated ordinary work");
} finally {
  sessionGoals.close(); graphs.close(); authority.close();
  await rm(root, { recursive: true, force: true });
}
console.log("session goal surfaces tests passed");
