/** 记忆设置的可见状态与清理入口；DOM 测试不替代人工视觉验收。 */
import assert from "node:assert/strict";
import { test } from "node:test";
import { defaultConfig } from "../src/config/schema.js";
import type { SettingsDraftContextValue } from "../src/desktop/renderer/src/components/settings/SettingsDraftContext.js";
import type { DesktopMemoryEntry, DesktopMemoryStats } from "../src/desktop/protocol.js";

test("仅剩归档事实时可清空全部，合成失败说明正确且归档可翻页", async () => {
  const { JSDOM } = await import("jsdom");
  const dom = new JSDOM("<div id='root'></div>", { url: "https://localhost/", pretendToBeVisual: true });
  const React = await import("react");
  const saved = new Map<string, PropertyDescriptor | undefined>();
  for (const [key, value] of Object.entries({
    window: dom.window, document: dom.window.document, navigator: dom.window.navigator,
    HTMLElement: dom.window.HTMLElement,
    requestAnimationFrame: dom.window.requestAnimationFrame.bind(dom.window),
    cancelAnimationFrame: dom.window.cancelAnimationFrame.bind(dom.window),
    MutationObserver: dom.window.MutationObserver,
    IS_REACT_ACT_ENVIRONMENT: true
  })) {
    saved.set(key, Object.getOwnPropertyDescriptor(globalThis, key));
    Object.defineProperty(globalThis, key, { configurable: true, value });
  }
  const { createRoot } = await import("react-dom/client");
  const { createServer } = await import("vite");
  const vite = await createServer({ configFile: false, server: { middlewareMode: true }, appType: "custom",
    optimizeDeps: { noDiscovery: true, entries: [] } });
  const { SettingsMemory } = await vite.ssrLoadModule("/src/desktop/renderer/src/components/settings/SettingsMemory.tsx") as typeof import("../src/desktop/renderer/src/components/settings/SettingsMemory.js");
  const { SettingsDraftContext } = await vite.ssrLoadModule("/src/desktop/renderer/src/components/settings/SettingsDraftContext.ts") as typeof import("../src/desktop/renderer/src/components/settings/SettingsDraftContext.js");
  const { SettingsDetailHostContext } = await vite.ssrLoadModule("/src/desktop/renderer/src/components/settings/SettingsDetailHostContext.ts") as typeof import("../src/desktop/renderer/src/components/settings/SettingsDetailHostContext.js");
  const root = createRoot(document.getElementById("root")!);
  const { act, createElement } = React;
  const policy = defaultConfig.context.memory;
  const run = { id: "run_1", status: "completed", trigger: "manual", examined: 2, exact: 0, expired: 0,
    similarity: 0, llm: 0, synthesisFailed: 1, archived: 0, written: 0, failed: 0,
    archivedExact: 0, archivedExpired: 0, archivedOrphan: 0, archivedSimilarity: 0, archivedLlm: 0,
    inputTokens: 0, outputTokens: 0, startedAt: "2026-09-25T00:00:00.000Z" } as const;
  const archived = Array.from({ length: 26 }, (_, index) => ({
    id: `archived_${index + 1}`, content: `Archived fact ${index + 1}`,
    archivedAt: "2026-09-24T00:00:00.000Z",
    mergedInto: index === 25 ? "older-chain-target" : undefined
  })) as DesktopMemoryEntry[];
  const stats = { configRevision: "1", revision: 1, settings: policy, totalEntries: 0,
    memoryStats: { total: 0, autoGenerated: 0, manualAdded: 0 }, maintenance: { state: "idle", lastRun: run } } as DesktopMemoryStats;
  let cleared = 0;
  const archiveOffsets: number[] = [];
  const notices: string[] = [];
  dom.window.confirm = () => true;
  try {
    const props = {
      models: [], embeddingModels: [], workspaceAvailable: true, sessionRunning: false,
      onLoadStats: async () => stats,
      onLoadEntries: async () => ({ revision: 1, entries: [], total: 0, offset: 0, limit: 20 }),
      onSearch: async () => [], onAdd: async () => stats, onUpdate: async () => stats,
      onDeleteEntry: async () => stats, onArchiveEntry: async (entryId: string) => ({ ...stats,
        mergedTarget: entryId === "archived_26" ? { id: "live-merged-target", content: "Current merged summary" } : null }),
      onLoadArchived: async (offset: number, limit: number, includeChains?: boolean) => { archiveOffsets.push(offset); return { revision: 1,
        entries: archived.slice(offset, offset + limit), chains: includeChains && offset === 25
          ? { archived_26: { finalId: "final-chain-target", depth: 2 } } : undefined,
        total: archived.length, offset, limit }; }, onRunSleep: async () => stats,
      onSleepStatus: async () => stats.maintenance, onSleepRuns: async () => [run],
      onPreviewSleep: async () => ({ available: false }), onCancelSleep: async () => ({ cancelled: false }),
      onClearMemory: async () => { cleared += 1; return stats; },
      onTestModelConfiguration: async () => ({ ok: false }), onLoadEmbeddingStatus: async () => { throw new Error("offline"); },
      onDownloadEmbeddingModel: async () => { throw new Error("unused"); },
      onCancelEmbeddingDownload: async () => { throw new Error("unused"); },
      onRebuildEmbeddingIndex: async () => { throw new Error("unused"); },
      onCancelEmbeddingRebuild: async () => { throw new Error("unused"); },
      onNotify: (message: string) => { notices.push(message); }
    } as unknown as Parameters<typeof SettingsMemory>[0];
    const context = { draft: { memory: policy }, snapshot: { memory: policy }, dirtyCount: 0,
      setMemory: () => undefined } as unknown as SettingsDraftContextValue;
    const dialogHost = document.createElement("div");
    document.body.append(dialogHost);
    await act(async () => { root.render(createElement(SettingsDetailHostContext.Provider, { value: dialogHost },
      createElement(SettingsDraftContext.Provider, { value: context }, createElement(SettingsMemory, props)))); });
    const button = [...document.querySelectorAll("button")].find((element) => element.textContent?.includes("清空全部"));
    assert.ok(button);
    assert.equal(button.disabled, false, "归档仍有事实时清空全部必须可执行");
    assert.match(document.body.textContent ?? "", /合成失败.*来源保留/u);
    assert.doesNotMatch(document.body.textContent ?? "", /合成失败（已进归档/u);
    const archiveDisclosure = [...document.querySelectorAll("button")].find((element) => element.textContent?.includes("归档记忆（26）"));
    assert.ok(archiveDisclosure);
    await act(async () => { archiveDisclosure.click(); });
    assert.match(document.body.textContent ?? "", /Archived fact 1/u);
    assert.doesNotMatch(document.body.textContent ?? "", /Archived fact 26/u);
    const nextArchivePage = document.querySelector<HTMLButtonElement>('button[aria-label="下一页归档记忆"]');
    assert.ok(nextArchivePage, "超过 25 条归档时必须有翻页入口");
    await act(async () => { nextArchivePage.click(); });
    assert.match(document.body.textContent ?? "", /Archived fact 26/u);
    assert.match(document.body.textContent ?? "", /→ #target（链深度 2）/u);
    assert.ok(archiveOffsets.includes(25), "第二页必须经分页入口读取，不能只切分首屏数组");
    const restoreButton = document.querySelector<HTMLButtonElement>('button[aria-label="恢复"]');
    assert.ok(restoreButton);
    await act(async () => { restoreButton.click(); });
    assert.ok(notices.some((notice) => notice.includes("Current merged summary") && notice.includes("手动删除")));
    assert.match(document.querySelector('[role="status"]')?.textContent ?? "", /Current merged summary/u);
    const previousArchivePage = document.querySelector<HTMLButtonElement>('button[aria-label="上一页归档记忆"]');
    assert.ok(previousArchivePage);
    await act(async () => { previousArchivePage.click(); });
    const manualRestoreButton = document.querySelector<HTMLButtonElement>('button[aria-label="恢复"]');
    assert.ok(manualRestoreButton);
    await act(async () => { manualRestoreButton.click(); });
    assert.doesNotMatch(document.body.textContent ?? "", /Current merged summary/u);
    assert.equal(notices.at(-1), "记忆已恢复");
    await act(async () => { button.click(); });
    assert.equal(cleared, 1);
  } finally {
    await act(() => root.unmount());
    await vite.close();
    dom.window.close();
    for (const [key, descriptor] of saved) {
      if (descriptor) Object.defineProperty(globalThis, key, descriptor);
      else Reflect.deleteProperty(globalThis, key);
    }
  }
});

test("已有事实时切换嵌入模型须先确认索引重建影响", async () => {
  const { JSDOM } = await import("jsdom");
  const dom = new JSDOM("<div id='root'></div>", { url: "https://localhost/", pretendToBeVisual: true });
  const saved = new Map<string, PropertyDescriptor | undefined>();
  for (const [key, value] of Object.entries({
    window: dom.window, document: dom.window.document, navigator: dom.window.navigator,
    HTMLElement: dom.window.HTMLElement,
    requestAnimationFrame: dom.window.requestAnimationFrame.bind(dom.window),
    cancelAnimationFrame: dom.window.cancelAnimationFrame.bind(dom.window),
    MutationObserver: dom.window.MutationObserver,
    IS_REACT_ACT_ENVIRONMENT: true
  })) {
    saved.set(key, Object.getOwnPropertyDescriptor(globalThis, key));
    Object.defineProperty(globalThis, key, { configurable: true, value });
  }
  const React = await import("react");
  const { act, createElement } = React;
  const { createRoot } = await import("react-dom/client");
  const { createServer } = await import("vite");
  const vite = await createServer({ configFile: false, server: { middlewareMode: true }, appType: "custom",
    optimizeDeps: { noDiscovery: true, entries: [] } });
  const { SettingsMemory } = await vite.ssrLoadModule("/src/desktop/renderer/src/components/settings/SettingsMemory.tsx") as typeof import("../src/desktop/renderer/src/components/settings/SettingsMemory.js");
  const { SettingsDraftContext } = await vite.ssrLoadModule("/src/desktop/renderer/src/components/settings/SettingsDraftContext.ts") as typeof import("../src/desktop/renderer/src/components/settings/SettingsDraftContext.js");
  const root = createRoot(document.getElementById("root")!);
  const policy = defaultConfig.context.memory;
  const stats = { configRevision: "1", revision: 1, settings: policy, totalEntries: 1,
    memoryStats: { total: 1, autoGenerated: 0, manualAdded: 1 }, maintenance: { state: "idle" } } as DesktopMemoryStats;
  const selected: unknown[] = [];
  const local = { ref: { kind: "local", model: "multilingual-e5-small" }, fingerprint: "local:test",
    displayName: "Multilingual E5 Small", recommendedThreshold: 0.7, source: "local", available: true, installed: true };
  try {
    const props = {
      models: [], embeddingModels: [local], workspaceAvailable: true, sessionRunning: false,
      onLoadStats: async () => stats,
      onLoadEntries: async () => ({ revision: 1, entries: [{ id: "memory_1", content: "A stored fact" }], total: 1, offset: 0, limit: 20 }),
      onSearch: async () => [], onAdd: async () => stats, onUpdate: async () => stats,
      onDeleteEntry: async () => stats, onArchiveEntry: async () => stats,
      onLoadArchived: async (offset: number, limit: number) => ({ revision: 1, entries: [], total: 0, offset, limit }), onRunSleep: async () => stats,
      onSleepStatus: async () => stats.maintenance, onSleepRuns: async () => [],
      onPreviewSleep: async () => ({ available: false }), onCancelSleep: async () => ({ cancelled: false }),
      onClearMemory: async () => stats,
      onTestModelConfiguration: async () => ({ ok: false }), onLoadEmbeddingStatus: async () => { throw new Error("offline"); },
      onDownloadEmbeddingModel: async () => { throw new Error("unused"); },
      onCancelEmbeddingDownload: async () => { throw new Error("unused"); },
      onRebuildEmbeddingIndex: async () => { throw new Error("unused"); },
      onCancelEmbeddingRebuild: async () => { throw new Error("unused"); },
      onNotify: () => undefined
    } as unknown as Parameters<typeof SettingsMemory>[0];
    const context = { draft: { memory: policy }, snapshot: { memory: policy }, dirtyCount: 0,
      setMemory: (next: unknown) => { selected.push(next); } } as unknown as SettingsDraftContextValue;
    const { SettingsDetailHostContext } = await vite.ssrLoadModule("/src/desktop/renderer/src/components/settings/SettingsDetailHostContext.ts") as typeof import("../src/desktop/renderer/src/components/settings/SettingsDetailHostContext.js");
    const dialogHost = document.createElement("div");
    document.body.append(dialogHost);
    await act(async () => { root.render(createElement(SettingsDetailHostContext.Provider, { value: dialogHost },
      createElement(SettingsDraftContext.Provider, { value: context }, createElement(SettingsMemory, props)))); });
    const picker = document.querySelector<HTMLElement>('[aria-label="选择嵌入模型"][role="combobox"]');
    assert.ok(picker);
    await act(async () => { picker.click(); });
    const localOption = [...document.querySelectorAll<HTMLButtonElement>('[role="option"]')].find((item) => item.textContent?.includes("Multilingual E5 Small"));
    assert.ok(localOption);
    await act(async () => { localOption.click(); });
    assert.equal(selected.length, 0, "确认前不得改变设置草稿");
    const dialog = document.querySelector<HTMLElement>('[role="dialog"]');
    assert.ok(dialog, "已有事实时应告知切换模型的召回影响");
    assert.match(dialog.textContent ?? "", /重建.*嵌入|嵌入.*重建/u);
    const cancel = [...dialog.querySelectorAll("button")].find((button) => button.textContent?.includes("取消"));
    assert.ok(cancel);
    await act(async () => { cancel.click(); });
    assert.equal(selected.length, 0, "取消后不应写入草稿");
    await act(async () => { picker.click(); });
    await act(async () => { localOption.click(); });
    const confirm = [...document.querySelectorAll<HTMLElement>('[role="dialog"] button')].find((button) => button.textContent?.includes("确认"));
    assert.ok(confirm);
    await act(async () => { confirm.click(); });
    assert.equal(selected.length, 1);
  } finally {
    await act(() => root.unmount());
    await vite.close();
    dom.window.close();
    for (const [key, descriptor] of saved) {
      if (descriptor) Object.defineProperty(globalThis, key, descriptor);
      else Reflect.deleteProperty(globalThis, key);
    }
  }
});

test("Sleep 预览展示跳过原因与合成建议，失败运行展示错误并可重试", async () => {
  const { JSDOM } = await import("jsdom");
  const dom = new JSDOM("<div id='root'></div>", { url: "https://localhost/", pretendToBeVisual: true });
  const saved = new Map<string, PropertyDescriptor | undefined>();
  for (const [key, value] of Object.entries({
    window: dom.window, document: dom.window.document, navigator: dom.window.navigator,
    HTMLElement: dom.window.HTMLElement,
    requestAnimationFrame: dom.window.requestAnimationFrame.bind(dom.window),
    cancelAnimationFrame: dom.window.cancelAnimationFrame.bind(dom.window),
    MutationObserver: dom.window.MutationObserver,
    IS_REACT_ACT_ENVIRONMENT: true
  })) {
    saved.set(key, Object.getOwnPropertyDescriptor(globalThis, key));
    Object.defineProperty(globalThis, key, { configurable: true, value });
  }
  const React = await import("react");
  const { act, createElement } = React;
  const { createRoot } = await import("react-dom/client");
  const { createServer } = await import("vite");
  const vite = await createServer({ configFile: false, server: { middlewareMode: true }, appType: "custom",
    optimizeDeps: { noDiscovery: true, entries: [] } });
  const { SettingsMemory } = await vite.ssrLoadModule("/src/desktop/renderer/src/components/settings/SettingsMemory.tsx") as typeof import("../src/desktop/renderer/src/components/settings/SettingsMemory.js");
  const { SettingsDraftContext } = await vite.ssrLoadModule("/src/desktop/renderer/src/components/settings/SettingsDraftContext.ts") as typeof import("../src/desktop/renderer/src/components/settings/SettingsDraftContext.js");
  const { SettingsDetailHostContext } = await vite.ssrLoadModule("/src/desktop/renderer/src/components/settings/SettingsDetailHostContext.ts") as typeof import("../src/desktop/renderer/src/components/settings/SettingsDetailHostContext.js");
  const root = createRoot(document.getElementById("root")!);
  const policy = { ...defaultConfig.context.memory, sleepEnabled: true };
  const run = { id: "failed_run", status: "failed", trigger: "manual", examined: 3, exact: 0, expired: 0,
    similarity: 0, llm: 0, synthesisFailed: 0, archived: 0, written: 0, failed: 1,
    archivedExact: 0, archivedExpired: 0, archivedOrphan: 0, archivedSimilarity: 0, archivedLlm: 0,
    inputTokens: 7, outputTokens: 5, startedAt: "2026-09-25T00:00:00.000Z", error: "模型暂不可用" } as const;
  const stats = { configRevision: "1", revision: 1, settings: policy, totalEntries: 0,
    memoryStats: { total: 0, autoGenerated: 0, manualAdded: 0 }, maintenance: { state: "idle", lastRun: run } } as DesktopMemoryStats;
  let previewCalls = 0;
  let runCalls = 0;
  const notices: string[] = [];
  const props = {
    models: [], embeddingModels: [], workspaceAvailable: true, sessionRunning: false,
    onLoadStats: async () => stats,
    onLoadEntries: async () => ({ revision: 1, entries: [], total: 0, offset: 0, limit: 20 }),
    onSearch: async () => [], onAdd: async () => stats, onUpdate: async () => stats,
    onDeleteEntry: async () => stats, onArchiveEntry: async () => stats,
    onLoadArchived: async (offset: number, limit: number) => ({ revision: 1, entries: [], total: 0, offset, limit }),
    onRunSleep: async () => { runCalls += 1; return stats; },
    onSleepStatus: async () => stats.maintenance, onSleepRuns: async () => [run],
    onPreviewSleep: async () => ++previewCalls === 1
      ? { available: true, entries: 3, temporaryToArchive: 0, archivedToDelete: 0, recentRuns: 1,
        skipped: "缺少当前模型向量", archiveProposed: [], synthesisProposed: [] }
      : { available: true, entries: 3, temporaryToArchive: 1, archivedToDelete: 0, recentRuns: 1,
        archiveProposed: [{ id: "old", content: "旧事实", reason: "similarity" }],
        synthesisProposed: [{ content: "合成后的新事实", durability: "permanent", sourceIds: ["old"] }],
        inputTokens: 12, outputTokens: 4 },
    onCancelSleep: async () => ({ cancelled: false }), onClearMemory: async () => stats,
    onTestModelConfiguration: async () => ({ ok: false }), onLoadEmbeddingStatus: async () => { throw new Error("offline"); },
    onDownloadEmbeddingModel: async () => { throw new Error("unused"); },
    onCancelEmbeddingDownload: async () => { throw new Error("unused"); },
    onRebuildEmbeddingIndex: async () => { throw new Error("unused"); },
    onCancelEmbeddingRebuild: async () => { throw new Error("unused"); },
    onNotify: (message: string) => { notices.push(message); }
  } as unknown as Parameters<typeof SettingsMemory>[0];
  const context = { draft: { memory: policy }, snapshot: { memory: policy }, dirtyCount: 0,
    setMemory: () => undefined } as unknown as SettingsDraftContextValue;
  try {
    await act(async () => { root.render(createElement(SettingsDetailHostContext.Provider, { value: document.body },
      createElement(SettingsDraftContext.Provider, { value: context }, createElement(SettingsMemory, props)))); });
    assert.match(document.body.textContent ?? "", /模型暂不可用/u);
    assert.match(document.body.textContent ?? "", /输入 7.*输出 5/u);
    const retry = [...document.querySelectorAll("button")].find((item) => item.textContent?.includes("重试整理"));
    assert.ok(retry);
    await act(async () => { retry.click(); });
    assert.equal(runCalls, 1);
    assert.ok(notices.some((message) => message.includes("整理失败") && message.includes("模型暂不可用")));
    const preview = [...document.querySelectorAll("button")].find((item) => item.textContent?.includes("预览下一次周期"));
    assert.ok(preview);
    await act(async () => { preview.click(); });
    assert.match(document.body.textContent ?? "", /缺少当前模型向量/u);
    await act(async () => { preview.click(); });
    assert.match(document.body.textContent ?? "", /拟归档 1 条/u);
    assert.match(document.body.textContent ?? "", /拟合成 1 条/u);
    assert.match(document.body.textContent ?? "", /合成后的新事实/u);
    assert.match(document.body.textContent ?? "", /输入 12.*输出 4/u);
    assert.doesNotMatch(document.body.textContent ?? "", /缺少当前模型向量/u);
  } finally {
    await act(() => root.unmount());
    await vite.close();
    dom.window.close();
    for (const [key, descriptor] of saved) {
      if (descriptor) Object.defineProperty(globalThis, key, descriptor);
      else Reflect.deleteProperty(globalThis, key);
    }
  }
});
