/** Sleep 设置页的下次运行日期应与当天已完成的运行状态一致；DOM 回归不替代人工视觉验收。 */
import assert from "node:assert/strict";
import { test } from "node:test";
import { defaultConfig } from "../src/config/schema.js";
import type { MemorySleepRun } from "../src/agent/context/memoryTypes.js";
import type { DesktopMemoryStats } from "../src/desktop/protocol.js";
import type { SettingsDraftContextValue } from "../src/desktop/renderer/src/components/settings/SettingsDraftContext.js";

test("当天手动 Sleep 已完成时设置页显示明天为下次运行日期", async () => {
  const { JSDOM } = await import("jsdom");
  const dom = new JSDOM("<div id='root'></div>", { url: "https://localhost/", pretendToBeVisual: true });
  const fixedNow = new Date(2026, 8, 26, 8, 0);
  const NativeDate = Date;
  class FixedDate extends NativeDate {
    constructor(value?: string | number | Date) {
      super(value === undefined ? fixedNow.valueOf() : value instanceof NativeDate ? value.valueOf() : value);
    }
    static override now(): number { return fixedNow.valueOf(); }
  }
  const saved = new Map<string, PropertyDescriptor | undefined>();
  for (const [key, value] of Object.entries({
    Date: FixedDate, window: dom.window, document: dom.window.document, navigator: dom.window.navigator,
    HTMLElement: dom.window.HTMLElement,
    requestAnimationFrame: dom.window.requestAnimationFrame.bind(dom.window),
    cancelAnimationFrame: dom.window.cancelAnimationFrame.bind(dom.window),
    MutationObserver: dom.window.MutationObserver,
    IS_REACT_ACT_ENVIRONMENT: true
  })) {
    saved.set(key, Object.getOwnPropertyDescriptor(globalThis, key));
    Object.defineProperty(globalThis, key, { configurable: true, value });
  }
  const React = await import("react");
  const { act, createElement } = React;
  const { createRoot } = await import("react-dom/client");
  const { createServer } = await import("vite");
  const vite = await createServer({ configFile: false, server: { middlewareMode: true }, appType: "custom",
    optimizeDeps: { noDiscovery: true, entries: [] } });
  const { SettingsMemory } = await vite.ssrLoadModule("/src/desktop/renderer/src/components/settings/SettingsMemory.tsx") as typeof import("../src/desktop/renderer/src/components/settings/SettingsMemory.js");
  const { SettingsDraftContext } = await vite.ssrLoadModule("/src/desktop/renderer/src/components/settings/SettingsDraftContext.ts") as typeof import("../src/desktop/renderer/src/components/settings/SettingsDraftContext.js");
  const root = createRoot(document.getElementById("root")!);
  const policy = { ...defaultConfig.context.memory, sleepEnabled: true, sleepTime: "20:00" };
  const completedRun = { id: "manual-today", status: "completed", trigger: "manual",
    examined: 0, written: 0, failed: 0, archived: 0, exact: 0, expired: 0, similarity: 0, llm: 0,
    archivedExact: 0, archivedExpired: 0, archivedOrphan: 0, archivedSimilarity: 0, archivedLlm: 0,
    synthesisFailed: 0, inputTokens: 0, outputTokens: 0,
    startedAt: new NativeDate(2026, 8, 26, 7, 0).toISOString(),
    finishedAt: new NativeDate(2026, 8, 26, 7, 1).toISOString() } as MemorySleepRun;
  const failedRun = { ...completedRun, id: "later-failure", status: "failed",
    startedAt: new NativeDate(2026, 8, 26, 7, 30).toISOString() } as MemorySleepRun;
  const stats = { configRevision: "1", revision: 1, settings: policy, totalEntries: 0,
    memoryStats: { total: 0, autoGenerated: 0, manualAdded: 0 },
    maintenance: { state: "idle", lastRun: failedRun } } as DesktopMemoryStats;
  let currentStatus = stats.maintenance;
  let currentRuns: MemorySleepRun[] = [completedRun, failedRun]; // Biny 持久层按开始时间升序返回。
  const props = {
    models: [], embeddingModels: [], workspaceAvailable: true, sessionRunning: false,
    onLoadStats: async () => stats,
    onLoadEntries: async () => ({ revision: 1, entries: [], total: 0, offset: 0, limit: 20 }),
    onSearch: async () => [], onAdd: async () => stats, onUpdate: async () => stats,
    onDeleteEntry: async () => stats, onArchiveEntry: async () => stats,
    onLoadArchived: async () => ({ revision: 1, entries: [], total: 0, offset: 0, limit: 25 }),
    onRunSleep: async () => stats, onSleepStatus: async () => currentStatus,
    onSleepRuns: async () => currentRuns, onPreviewSleep: async () => ({ available: false }),
    onCancelSleep: async () => ({ cancelled: false }), onClearMemory: async () => stats,
    onTestModelConfiguration: async () => ({ ok: false }),
    onLoadEmbeddingStatus: async () => { throw new Error("offline"); },
    onDownloadEmbeddingModel: async () => { throw new Error("unused"); },
    onCancelEmbeddingDownload: async () => { throw new Error("unused"); },
    onRebuildEmbeddingIndex: async () => { throw new Error("unused"); },
    onCancelEmbeddingRebuild: async () => { throw new Error("unused"); },
    onNotify: () => undefined
  } as unknown as Parameters<typeof SettingsMemory>[0];
  const context = { draft: { memory: policy }, snapshot: { memory: policy }, dirtyCount: 0,
    setMemory: () => undefined } as unknown as SettingsDraftContextValue;
  try {
    await act(async () => { root.render(createElement(SettingsDraftContext.Provider, { value: context }, createElement(SettingsMemory, props))); });
    assert.match(document.querySelector("#memory-sleep .activity-memory-heading-row")?.textContent ?? "", /下次：2026-09-27 20:00/u);
    currentRuns = [completedRun, ...Array.from({ length: 5 }, (_, index) => ({
      ...failedRun, id: `newer-failure-${index}`,
      startedAt: new NativeDate(2026, 8, 26, 7, 10 + index).toISOString()
    }))];
    currentStatus = { ...currentStatus, lastRun: completedRun }; // 状态快照落后时不能把第六次旧成功算进最近 5 次。
    await act(async () => { root.render(createElement(SettingsDraftContext.Provider, { value: context },
      createElement(SettingsMemory, { ...props, hidden: true }))); });
    await act(async () => { root.render(createElement(SettingsDraftContext.Provider, { value: context },
      createElement(SettingsMemory, props))); });
    assert.match(document.querySelector("#memory-sleep .activity-memory-heading-row")?.textContent ?? "", /下次：2026-09-26 20:00/u);
  } finally {
    await act(() => root.unmount());
    await vite.close();
    dom.window.close();
    for (const [key, descriptor] of saved) {
      if (descriptor) Object.defineProperty(globalThis, key, descriptor);
      else Reflect.deleteProperty(globalThis, key);
    }
  }
});
