/** 睡眠整理的设置页状态会随外部维护运行刷新；DOM 回归不替代视觉验收。 */
import assert from "node:assert/strict";
import { test } from "node:test";
import { defaultConfig } from "../src/config/schema.js";
import type { MemoryMaintenanceStatus, MemorySleepRun } from "../src/agent/context/memoryTypes.js";
import type { DesktopMemoryStats } from "../src/desktop/protocol.js";
import type { SettingsDraftContextValue } from "../src/desktop/renderer/src/components/settings/SettingsDraftContext.js";

test("设置页轮询显示定时 Sleep 的阶段和累计归档数，完成后清除运行态", async () => {
  const { JSDOM } = await import("jsdom");
  const dom = new JSDOM("<div id='root'></div>", { url: "https://localhost/", pretendToBeVisual: true });
  const saved = new Map<string, PropertyDescriptor | undefined>();
  for (const [key, value] of Object.entries({
    window: dom.window, document: dom.window.document, navigator: dom.window.navigator,
    HTMLElement: dom.window.HTMLElement,
    requestAnimationFrame: dom.window.requestAnimationFrame.bind(dom.window),
    cancelAnimationFrame: dom.window.cancelAnimationFrame.bind(dom.window),
    MutationObserver: dom.window.MutationObserver,
    IS_REACT_ACT_ENVIRONMENT: true
  })) {
    saved.set(key, Object.getOwnPropertyDescriptor(globalThis, key));
    Object.defineProperty(globalThis, key, { configurable: true, value });
  }
  const React = await import("react");
  const { act, createElement } = React;
  const { createRoot } = await import("react-dom/client");
  const { createServer } = await import("vite");
  const vite = await createServer({ configFile: false, server: { middlewareMode: true }, appType: "custom",
    optimizeDeps: { noDiscovery: true, entries: [] } });
  const { SettingsMemory } = await vite.ssrLoadModule("/src/desktop/renderer/src/components/settings/SettingsMemory.tsx") as typeof import("../src/desktop/renderer/src/components/settings/SettingsMemory.js");
  const { SettingsDraftContext } = await vite.ssrLoadModule("/src/desktop/renderer/src/components/settings/SettingsDraftContext.ts") as typeof import("../src/desktop/renderer/src/components/settings/SettingsDraftContext.js");
  const root = createRoot(document.getElementById("root")!);
  const originalSetInterval = dom.window.setInterval.bind(dom.window);
  let poll: (() => void) | undefined;
  dom.window.setInterval = ((handler: TimerHandler, timeout?: number, ...args: unknown[]) => {
    if (timeout === 1_000 && typeof handler === "function") { poll = () => handler(...args); return 42; }
    return originalSetInterval(handler, timeout, ...args);
  }) as typeof dom.window.setInterval;
  const policy = { ...defaultConfig.context.memory, sleepEnabled: true };
  const running = { id: "run-progress", status: "running", trigger: "scheduled", examined: 4,
    written: 0, failed: 0, archived: 0, exact: 0, expired: 0, similarity: 0, llm: 0,
    archivedExact: 0, archivedExpired: 0, archivedOrphan: 0, archivedSimilarity: 0, archivedLlm: 0,
    synthesisFailed: 0, inputTokens: 0, outputTokens: 0, startedAt: "2026-09-26T00:00:00.000Z" } as MemorySleepRun;
  let current: MemoryMaintenanceStatus = { state: "running", progressStage: "exact", eligible: 4,
    processed: 0, written: 0, failed: 0, lastRun: running };
  let statusFailure = false;
  let archivedTotal = 0;
  let runs: MemorySleepRun[] = [];
  const stats = { configRevision: "1", revision: 1, settings: policy, totalEntries: 4,
    memoryStats: { total: 4, autoGenerated: 0, manualAdded: 4 }, maintenance: current } as DesktopMemoryStats;
  try {
    const props = {
      models: [], embeddingModels: [], workspaceAvailable: true, sessionRunning: false,
      onLoadStats: async () => ({ ...stats, maintenance: current }),
      onLoadEntries: async () => ({ revision: 1, entries: [], total: 4, offset: 0, limit: 20 }),
      onSearch: async () => [], onAdd: async () => stats, onUpdate: async () => stats,
      onDeleteEntry: async () => stats, onArchiveEntry: async () => stats,
      onLoadArchived: async () => ({ revision: 1, entries: [], total: archivedTotal, offset: 0, limit: 25 }),
      onRunSleep: async () => stats, onSleepStatus: async () => {
        if (statusFailure) throw new Error("宿主暂时不可用");
        return current;
      },
      onSleepRuns: async () => runs, onPreviewSleep: async () => ({ available: false }),
      onCancelSleep: async () => ({ cancelled: false }), onClearMemory: async () => stats,
      onTestModelConfiguration: async () => ({ ok: false }),
      onLoadEmbeddingStatus: async () => { throw new Error("offline"); },
      onDownloadEmbeddingModel: async () => { throw new Error("unused"); },
      onCancelEmbeddingDownload: async () => { throw new Error("unused"); },
      onRebuildEmbeddingIndex: async () => { throw new Error("unused"); },
      onCancelEmbeddingRebuild: async () => { throw new Error("unused"); },
      onNotify: () => undefined
    } as unknown as Parameters<typeof SettingsMemory>[0];
    const context = { draft: { memory: policy }, snapshot: { memory: policy }, dirtyCount: 0,
      setMemory: () => undefined } as unknown as SettingsDraftContextValue;
    await act(async () => { root.render(createElement(SettingsDraftContext.Provider, { value: context }, createElement(SettingsMemory, props))); });
    assert.match(document.body.textContent ?? "", /当前阶段：精确去重/u);
    assert.ok(poll, "设置页应持续读取外部 Sleep 状态");
    current = { ...current, progressStage: "similarity", lastRun: { ...running,
      exact: 2, expired: 1, similarity: 3, llm: 4, archivedExact: 2,
      archivedExpired: 1, archivedSimilarity: 3, archivedLlm: 4, archived: 10 } };
    await act(async () => { poll?.(); });
    assert.match(document.body.textContent ?? "", /当前阶段：相似合并/u);
    assert.match(document.body.textContent ?? "", /已归档 10 条/u);
    assert.match(document.body.textContent ?? "", /精确重复 2.*过期 1.*相似合并 3.*LLM 合并 4/u,
      "进行中的阶段应展示四类累计归档数");
    statusFailure = true;
    await act(async () => { poll?.(); });
    assert.doesNotMatch(document.body.textContent ?? "", /当前阶段：/u);
    assert.match(document.querySelector('[role="alert"]')?.textContent ?? "", /宿主暂时不可用/u);
    statusFailure = false;
    await act(async () => { poll?.(); });
    assert.match(document.body.textContent ?? "", /当前阶段：相似合并/u);
    current = { ...current, state: "idle", progressStage: undefined,
      lastRun: { ...current.lastRun!, status: "completed", finishedAt: "2026-09-26T00:01:00.000Z" } };
    await act(async () => { poll?.(); });
    assert.doesNotMatch(document.body.textContent ?? "", /当前阶段：/u);
    assert.match(document.body.textContent ?? "", /上次：completed/u);
    const missedRun = { ...running, id: "missed-run", status: "completed", trigger: "scheduled",
      archived: 11, finishedAt: "2026-09-26T00:02:00.000Z" } as MemorySleepRun;
    current = { ...current, lastRun: missedRun };
    runs = [missedRun];
    archivedTotal = 11;
    await act(async () => { poll?.(); });
    assert.match(document.body.textContent ?? "", /归档记忆（11）/u,
      "两次轮询之间完成的定时整理也须刷新归档数量");
    assert.match(document.body.textContent ?? "", /近期运行（1）/u);
    await act(async () => { root.render(createElement(SettingsDraftContext.Provider, { value: context },
      createElement(SettingsMemory, { ...props, hidden: true }))); });
    current = { ...current, state: "running", progressStage: "expired",
      lastRun: { ...running, id: "second-run", progressStage: "expired" } };
    await act(async () => { root.render(createElement(SettingsDraftContext.Provider, { value: context },
      createElement(SettingsMemory, { ...props, hidden: false }))); });
    assert.match(document.body.textContent ?? "", /当前阶段：清理过期/u, "重新打开设置页须读取最新定时运行");
  } finally {
    await act(() => root.unmount());
    await vite.close();
    dom.window.close();
    for (const [key, descriptor] of saved) {
      if (descriptor) Object.defineProperty(globalThis, key, descriptor);
      else Reflect.deleteProperty(globalThis, key);
    }
  }
});
