/** 记忆设置页显示派生索引缺口；DOM 断言不代替人工界面验收。 */
import assert from "node:assert/strict";
import { test } from "node:test";
import { defaultConfig } from "../src/config/schema.js";
import type { DesktopMemoryEmbeddingStatus, DesktopMemoryStats } from "../src/desktop/protocol.js";
import type { SettingsDraftContextValue } from "../src/desktop/renderer/src/components/settings/SettingsDraftContext.js";

test("恢复的事实尚未索引时显示部分不可搜索并允许重建", async () => {
  const { JSDOM } = await import("jsdom");
  const dom = new JSDOM("<div id='root'></div>", { url: "https://localhost/", pretendToBeVisual: true });
  const saved = new Map<string, PropertyDescriptor | undefined>();
  for (const [key, value] of Object.entries({
    window: dom.window, document: dom.window.document, navigator: dom.window.navigator,
    HTMLElement: dom.window.HTMLElement,
    requestAnimationFrame: dom.window.requestAnimationFrame.bind(dom.window),
    cancelAnimationFrame: dom.window.cancelAnimationFrame.bind(dom.window),
    MutationObserver: dom.window.MutationObserver,
    IS_REACT_ACT_ENVIRONMENT: true
  })) {
    saved.set(key, Object.getOwnPropertyDescriptor(globalThis, key));
    Object.defineProperty(globalThis, key, { configurable: true, value });
  }
  const React = await import("react");
  const { act, createElement } = React;
  const { createRoot } = await import("react-dom/client");
  const { createServer } = await import("vite");
  const vite = await createServer({ configFile: false, server: { middlewareMode: true }, appType: "custom",
    optimizeDeps: { noDiscovery: true, entries: [] } });
  const { SettingsMemory } = await vite.ssrLoadModule("/src/desktop/renderer/src/components/settings/SettingsMemory.tsx") as typeof import("../src/desktop/renderer/src/components/settings/SettingsMemory.js");
  const { SettingsDraftContext } = await vite.ssrLoadModule("/src/desktop/renderer/src/components/settings/SettingsDraftContext.ts") as typeof import("../src/desktop/renderer/src/components/settings/SettingsDraftContext.js");
  const root = createRoot(document.getElementById("root")!);
  const policy = defaultConfig.context.memory;
  const stats = { configRevision: "1", revision: 2, settings: policy, totalEntries: 2,
    memoryStats: { total: 2, autoGenerated: 0, manualAdded: 2 }, maintenance: { state: "idle" } } as DesktopMemoryStats;
  const descriptor = { ref: { kind: "provider", provider: "test", model: "embed" }, fingerprint: "test:embed",
    displayName: "Test Embedding", recommendedThreshold: 0.7, source: "provider", available: true } as const;
  const pending = { activeModel: descriptor.ref, models: [descriptor], localModels: [], index: {},
    totalEntries: 2, indexedEntries: 1, pendingEntries: 1, needsRebuild: false,
    degradedReason: "1 条记忆等待索引，未索引条目暂不能被搜索。" } as DesktopMemoryEmbeddingStatus;
  let rebuilds = 0;
  try {
    const props = {
      models: [], embeddingModels: [descriptor], workspaceAvailable: true, sessionRunning: false,
      onLoadStats: async () => stats,
      onLoadEntries: async () => ({ revision: 2, entries: [], total: 2, offset: 0, limit: 20 }),
      onSearch: async () => [], onAdd: async () => stats, onUpdate: async () => stats,
      onDeleteEntry: async () => stats, onArchiveEntry: async () => stats,
      onLoadArchived: async () => ({ revision: 2, entries: [], total: 0, offset: 0, limit: 25 }),
      onRunSleep: async () => stats, onSleepStatus: async () => stats.maintenance,
      onSleepRuns: async () => [], onPreviewSleep: async () => ({ available: false }),
      onCancelSleep: async () => ({ cancelled: false }), onClearMemory: async () => stats,
      onTestModelConfiguration: async () => ({ ok: false }), onLoadEmbeddingStatus: async () => pending,
      onDownloadEmbeddingModel: async () => pending, onCancelEmbeddingDownload: async () => ({ cancelled: false, status: pending }),
      onRebuildEmbeddingIndex: async () => { rebuilds += 1; return { ...pending, indexedEntries: 2, pendingEntries: 0, degradedReason: undefined }; },
      onCancelEmbeddingRebuild: async () => ({ cancelled: false, status: pending }),
      onNotify: () => undefined
    } as unknown as Parameters<typeof SettingsMemory>[0];
    const context = { draft: { memory: policy }, snapshot: { memory: policy }, dirtyCount: 0,
      setMemory: () => undefined } as unknown as SettingsDraftContextValue;
    await act(async () => { root.render(createElement(SettingsDraftContext.Provider, { value: context }, createElement(SettingsMemory, props))); });
    assert.match(document.body.textContent ?? "", /1 条记忆.*未索引.*不能.*搜索/u);
    assert.doesNotMatch(document.body.textContent ?? "", /自动记忆召回已暂停/u);
    const rebuild = [...document.querySelectorAll("button")].find((button) => button.textContent === "立即重建");
    assert.ok(rebuild);
    assert.equal(rebuild.disabled, false);
    await act(async () => { rebuild.click(); });
    assert.equal(rebuilds, 1);
    assert.doesNotMatch(document.body.textContent ?? "", /1 条记忆.*未索引.*不能.*搜索/u);
  } finally {
    await act(() => root.unmount());
    await vite.close();
    dom.window.close();
    for (const [key, descriptor] of saved) {
      if (descriptor) Object.defineProperty(globalThis, key, descriptor);
      else Reflect.deleteProperty(globalThis, key);
    }
  }
});
