/** 验证显示边界与位置对应组件的公开输出；视觉和点击验收仍交给用户。 */
import assert from "node:assert/strict";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { ThreadBriefContext } from "../src/desktop/renderer/src/threadBrief/context.js";
import { ProjectSuggestionBanner } from "../src/desktop/renderer/src/threadBrief/ProjectSuggestionBanner.js";
import { ThreadBriefSessionState } from "../src/desktop/renderer/src/threadBrief/ThreadBriefSessionState.js";
import { ThreadBriefCard } from "../src/desktop/renderer/src/components/settings/ThreadBriefCard.js";
import { defaultThreadBriefSettings } from "../src/session/threadBriefTypes.js";
import type { DesktopThreadBriefSnapshot } from "../src/desktop/threadBriefProtocol.js";
const snapshot: DesktopThreadBriefSnapshot = { config: defaultThreadBriefSettings, defaults: defaultThreadBriefSettings, enabledAt: "2026-09-22", projects: [], briefs: [], suggestions: [{ id: "suggestion", signature: "signature", kind: "create", status: "open", name: "编辑器", brief: "项目理解", focus: "准备发布", reason: "持续推进编辑器发布", threads: [{ sessionId: "related", projectId: "project", title: "编辑器发布", createdAt: "2026-09-22" }], createdAt: "2026-09-22" }] };
const render = (child: React.ReactElement): string => renderToStaticMarkup(createElement(ThreadBriefContext.Provider, { value: { snapshot, request: async () => snapshot } }, child));
assert.equal(render(createElement(ProjectSuggestionBanner, { sessionId: "unrelated" })), "", "无关对话不展示项目建议");
const banner = render(createElement(ProjectSuggestionBanner, { sessionId: "related" }));
assert.match(banner, /看看草稿/u);
assert.doesNotMatch(banner, /<dialog|项目理解/u, "草稿只能点击当前对话的提示打开");
snapshot.suggestions[0]!.status = "dismissed";
assert.equal(render(createElement(ProjectSuggestionBanner, { sessionId: "related" })), "", "已忽略建议不重复出现");
const settings = render(createElement(ThreadBriefCard));
assert.equal((settings.match(/role="switch"/gu) ?? []).length, 3);
assert.doesNotMatch(settings, /看看草稿|项目理解|编辑器发布|摘要列表/u, "设置页只配置功能，不浏览摘要或项目建议");
snapshot.config = { ...snapshot.config, enabled: false };
const disabledSettings = render(createElement(ThreadBriefCard));
assert.equal((disabledSettings.match(/disabled=""/gu) ?? []).length, 2, "关闭总开关仅禁用两个从属开关，数字门槛仍可编辑");
assert.doesNotMatch(disabledSettings, /<input[^>]*disabled/u);
assert.equal(render(createElement(ThreadBriefSessionState, { sessionId: "related" })), "", "没有摘要结果就不臆造待办");
snapshot.briefs.push({ ...snapshot.suggestions[0]!.threads[0]!, brief: { topic: "编辑器", goal: "发布", objects: [], conclusions: [], followUp: { what: "发布", quote: "明天发布" } }, contentHash: "hash", materialLength: 500, userTurns: 2, updatedAt: "2026-09-22", status: "todo", statusManual: false, autoTodo: { what: "发布", quote: "明天发布", at: "2026-09-22" } });
assert.match(render(createElement(ThreadBriefSessionState, { sessionId: "related" })), /自动标记待办：发布/u);
console.log("thread brief presentation boundary tests passed");
