/** Only synthetic data; render the production component and complete stylesheet cascade. */
import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { memoryPolicySchema } from "../../../src/personalization/index.js";
import { SettingsMemory } from "../../../src/desktop/renderer/src/components/settings/SettingsMemory.js";
import { SettingsDraftContext, type SettingsDraftContextValue } from "../../../src/desktop/renderer/src/components/settings/SettingsDraftContext.js";
import type { DesktopMemoryStats } from "../../../src/desktop/protocol.js";
import type { MemorySleepRun } from "../../../src/agent/context/memoryTypes.js";
import "../../../src/desktop/renderer/src/styles/layers.css";
import "./shell.css";

const policy = memoryPolicySchema.parse({});
const run: MemorySleepRun = {
  id: "fixture-run", status: "completed", trigger: "scheduled", startedAt: "2026-01-01T03:00:00.000Z",
  examined: 0, written: 0, failed: 0, archived: 0, exact: 0, expired: 0, similarity: 0, llm: 0,
  archivedExact: 0, archivedExpired: 0, archivedOrphan: 0, archivedSimilarity: 0, archivedLlm: 0,
  synthesisFailed: 0, inputTokens: 0, outputTokens: 0
};
const stats = {
  configRevision: "fixture", revision: 1, settings: policy, totalEntries: 0,
  memoryStats: { total: 0, autoGenerated: 0, manualAdded: 0 }, maintenance: { state: "idle" }
} as DesktopMemoryStats;
const page = async (offset: number, limit: number) => ({ revision: 1, entries: [], total: 0, offset, limit });
const unused = async (): Promise<never> => { throw new Error("No external services in the renderer fixture"); };
let loads = 0;
// Stable callbacks avoid turning a policy edit into an unrelated reload effect.
const props: Parameters<typeof SettingsMemory>[0] = {
  models: [], embeddingModels: [], workspaceAvailable: true, sessionRunning: false,
  onLoadStats: async () => {
    document.getElementById("root")!.dataset.loads = String(++loads);
    return stats;
  }, onLoadEntries: page, onLoadArchived: page, onSearch: async () => [],
  onAdd: unused, onUpdate: unused, onDeleteEntry: unused, onArchiveEntry: unused,
  onRunSleep: unused, onSleepStatus: async () => stats.maintenance, onSleepRuns: async () => [run],
  onPreviewSleep: unused, onCancelSleep: unused, onClearMemory: unused, onTestModelConfiguration: unused,
  onLoadEmbeddingStatus: unused, onDownloadEmbeddingModel: unused, onCancelEmbeddingDownload: unused,
  onRebuildEmbeddingIndex: unused, onCancelEmbeddingRebuild: unused, onNotify: () => undefined
};

function Fixture(): React.JSX.Element {
  const [memory, setMemory] = useState(policy);
  const context = {
    draft: { memory }, snapshot: { memory: policy }, dirtyCount: 0, setMemory
  } as unknown as SettingsDraftContextValue;
  return <div className="memory-fixture desktop-settings-dialog">
    <div className="settings-modal"><div className="settings-scroll">
      <SettingsDraftContext.Provider value={context}><SettingsMemory {...props} /></SettingsDraftContext.Provider>
    </div></div>
  </div>;
}

createRoot(document.getElementById("root")!).render(<Fixture />);
