/** Requires build:cli. Prepare complete offline QA config; never launch, sign or grant TCC. */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { configSchema, defaultConfig } from "../dist/config/schema.js";
const root = fileURLToPath(new URL("../", import.meta.url));
const revision = process.argv[2] ?? "revision-2";
if (!/^[a-z0-9-]+$/.test(revision)) throw new Error("Invalid QA revision directory");
const artifacts = path.join(root, "artifacts/computer-use", revision);
const profile = path.join(artifacts, "qa-profile");
await mkdir(path.join(profile, "agent"), { recursive: true, mode: 0o700 });
await mkdir(path.join(profile, "desktop"), { recursive: true, mode: 0o700 });
const config = structuredClone(defaultConfig);
config.defaultModel = "synthetic-only";
config.providers = { "cua-qa": { type: "openai-compatible", baseUrl: "http://127.0.0.1:9/v1", apiKey: "synthetic-only-no-network" } };
config.models = { "synthetic-only": { provider: "cua-qa", model: "synthetic-only", displayName: "Synthetic only · offline", supportsTools: true } };
config.activity = { ...config.activity, enabled: false, inputMonitoringEnabled: false, browserPollIntervalMs: 0, ocrEnabled: false, outputDirectory: path.join(profile, "activity-records") };
config.heartbeat.enabled = false;
config.crystal.passiveEnabled = false;
config.crystal.semanticScanEnabled = false;
config.context.identity.enabled = false;
config.context.identity.userEnabled = false;
config.context.memory.enabled = false;
config.context.memory.useMemories = false;
config.context.memory.generateMemories = false;
config.context.memory.sleepEnabled = false;
config.context.memory.useLlm = false;
config.extensions.skills = [];
config.extensions.plugins = [];
config.extensions.globalPlugins = [];
config.permission.mode = "ask";
config.sandbox.allowNetwork = false;
const validated = configSchema.parse(config);
await writeFile(path.join(profile, "agent/config.json"), JSON.stringify(validated, null, 2), { mode: 0o600 });
await writeFile(path.join(artifacts, "qa-builder.json"), JSON.stringify({ extends: path.join(root, "electron-builder.yml"), appId: "com.biny.desktop.cua-qa", productName: "Biny Cua QA", directories: { output: path.join(artifacts, "package") }, mac: { identity: null }, forceCodeSigning: false }, null, 2));
console.log(JSON.stringify({ profile, packageName: "Biny Cua QA", bundleId: "com.biny.desktop.cua-qa", validFullSchema: true, passiveCollection: false, modelDestination: validated.providers["cua-qa"].baseUrl, signed: false, launched: false, permissionsRequested: false }));
